### ISSUE TITLE
Broken! Enabling Breaks Gear Wheel Menu

### ISSUE THREAD

**Issue by hifihedgehog** [MonDiscourse/md-composer-extras#13]
See video:

https://github.com/MonDiscourse/md-composer-extras/assets/16614343/7a968709-f89c-4693-92f8-559c26feb21e

**Comment by MonDiscourse** [comment]
I assume you use the Formatting toolbar plugin also, you should delete this component or the plugin to make it work

The component on its own, works on the latest version
![165238](https://github.com/MonDiscourse/md-composer-extras/assets/95508132/061dc085-d828-49a5-aa8d-a0659ac2813e)

**Comment by hifihedgehog** [comment]
Hi @MonDiscourse. I meant to post this in your https://github.com/MonDiscourse/discourse-strikethrough repository. The issue is with discourse-strikethrough. I'll close this and repost there.
